apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-openapi-definition
  annotations:
    description: st2 openapi.yaml.j2 definition with fixes for some endpoints
  labels:
    {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
  openapi.yaml.j2: |
{{ .Files.Get "st2/openapi.yaml.j2" | indent 4 }}
