{{- if index .Values "stackstorm-ha" "serviceAccount" "create" }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade, pre-rollback
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - list
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade, pre-rollback
subjects:
- kind: ServiceAccount
  name: {{ include "st2.serviceaccount.name" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: ""
{{- end }}
